package com.hughie.dandao.common.item;

import com.hughie.dandao.common.effect.ModEffects;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;

public class ModFoodProperties {
    public static final FoodProperties FUTIDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 30*20, 2), 1)
            .build();
    public static final FoodProperties HUICHUNDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.HEAL, 1, 1), 1)
            .build();
    public static final FoodProperties LONGLIDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 10*60*20, 9), 1)
            .effect(() ->new MobEffectInstance(MobEffects.ABSORPTION, 10*60*20, 4), 1)
            .build();
    public static final FoodProperties SHOULIDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.DAMAGE_BOOST, 10*60*20, 4), 1)
            .effect(() ->new MobEffectInstance(MobEffects.ABSORPTION, 10*60*20, 1), 1)
            .build();
    public static final FoodProperties JIEDUDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .effect(() -> new MobEffectInstance(ModEffects.POISON_IMMUNE.get(), 5*60*20), 1)
            .alwaysEat()
            .build();
    public static final FoodProperties BIGUDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.SATURATION, 5*60*20), 1)
            .build();
    public static final FoodProperties JIYUNDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(ModEffects.FLIGHT.get(), 10*60*20), 1)
            .build();
    public static final FoodProperties JULINGDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.LUCK, 10*60*20), 1)
            .effect(() -> new MobEffectInstance(ModEffects.XP_BOOST.get(), 10*60*20), 1)
            .build();
    public static final FoodProperties HUIGUANGDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(ModEffects.TO_DIE_HARD_INACTIVE.get(), 2*60*20), 1)
            .build();
    public static FoodProperties JIUSIPOYUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(ModEffects.NO_TURNING_BACK.get(), 2*60*20), 1)
            .build();
    public static FoodProperties FANMINGDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(ModEffects.SOUL_LOCK.get(), 2*60*20), 1)
            .build();
    public static FoodProperties XUEHUNDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(ModEffects.SURA.get(), 5*60*20), 1)
            .build();
    public static FoodProperties HUOHUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.FIRE_RESISTANCE, 10*60*20), 1)
            .build();
    public static FoodProperties SHUIHUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.CONDUIT_POWER, 10*60*20), 1)
            .effect(() -> new MobEffectInstance(MobEffects.DOLPHINS_GRACE, 10*60*20), 1)
            .build();
    public static FoodProperties MUHUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.REGENERATION, 60*20, 5), 1)
            .effect(() -> new MobEffectInstance(MobEffects.HEALTH_BOOST, 10*60*20, 3), 1)
            .build();
    public static FoodProperties TUHUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.DIG_SPEED, 10*60*20, 5), 1)
            .effect(() -> new MobEffectInstance(MobEffects.SLOW_FALLING, 10*60*20), 1)
            .effect(() -> new MobEffectInstance(MobEffects.NIGHT_VISION, 10*60*20), 1)
            .build();
    public static FoodProperties JINHUANDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 2*60*20, 5), 1)
            .build();
    public static FoodProperties HUAIDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.CONFUSION, 2*60*20), 0.5f)
            .effect(() -> new MobEffectInstance(MobEffects.POISON, 30*20), 0.2f)
            .effect(() -> new MobEffectInstance(ModEffects.HEARTBROKEN.get(), 3*60*20), 0.55f)
            .effect(() -> new MobEffectInstance(ModEffects.TO_DIE_HARD_ACTIVE.get(), 10*20), 0.4f)
            .build();

    public static FoodProperties FENGXINGDAN = new FoodProperties.Builder()
            .nutrition(1)
            .fast()
            .saturationMod(0.25f)
            .alwaysEat()
            .effect(() -> new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 10*60*20, 4), 1f)
            .effect(() -> new MobEffectInstance(MobEffects.JUMP, 10*60*20, 2), 1)
            .build();
}
